name: arcane_helper_utils
description: "A variety of utilities for Flutter and Dart"
version: 1.0.0
homepage: https://github.com/hanskokx/arcane_helper_utils

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  week_number: ^1.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
