name: arcane_helper_utils
description: Provides a variety of helpful utilities and extensions for Flutter
  and Dart.
version: 1.0.2
repository: https://github.com/hanskokx/arcane_helper_utils
issue_tracker: https://github.com/hanskokx/arcane_helper_utils/issues

topics:
  - extensions
  - arcane-framework
  - helper-utils

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  week_number: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
