name: arcane_helper_utils
description: Provides a variety of helpful utilities and extensions for Flutter
  and Dart.
version: 1.2.1
repository: https://github.com/hanskokx/arcane_helper_utils
issue_tracker: https://github.com/hanskokx/arcane_helper_utils/issues

topics:
  - extensions
  - arcane-framework
  - helper-utils

environment:
  sdk: ^3.5.2

dependencies:
  freezed_annotation: ^2.4.4
  week_number: ^1.1.0

dev_dependencies:
  arcane_analysis: ^1.0.1
